version: 2
jobs:
  build:
    docker:
      - image: node:7.7.3
      - image: mikesir87/aws-cli:1.11.72
        name: awscli
        command: sleep 300
    working_directory: ~/st2apidocs
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          command: docker ps
      - run:
          name: Fetch latest StackStorm OpenAPI spec
          command: curl -o openapi.yaml https://raw.githubusercontent.com/StackStorm/st2/${ST2_GITREV:-$CIRCLE_BRANCH}/st2common/st2common/openapi.yaml
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Lint
          command: npm run lint --silent
      - run:
          name: Test
          command: npm test
      - run:
          name: Install doc generator
          command: npm install -g https://github.com/StackStorm/st2apidocgen
      - run:
          name: Generate API documentation
          command: st2apidocgen --render --output
      - store_artifacts:
          path: ~/st2apidocs/build
          destination: build
      - deploy:
          command: |
            docker exec awscli aws configure set preview.cloudfront true
            docker cp build/ awscli:/build
      - deploy:
          name: Deploying to S3
          command: |
            find ~/st2apidocs/build | sed 's|[^/]*/|  |g'
            docker exec awscli aws s3 sync /build s3://api-staging.stackstorm.com/${CIRCLE_BUILD_NUM} --region ${REGION}
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker exec awscli aws s3 sync /build s3://api.stackstorm.com/ --region ${REGION} --delete
              docker exec awscli aws cloudfront create-invalidation --distribution-id=${DISTRIBUTION_ID} --paths="/*"
            fi
