version: 2
jobs:
  build:
    docker:
      - image: node:7.7.3
    working_directory: ~/st2apidocs
    steps:
      - checkout
      - run:
          name: Fetch latest StackStorm OpenAPI spec
          command: curl -o openapi.yaml https://raw.githubusercontent.com/StackStorm/st2/${ST2_GITREV:-$CIRCLE_BRANCH}/st2common/st2common/openapi.yaml
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Lint
          command: npm run lint --silent
      - run:
          name: Test
          command: npm test
      - run:
          name: Install doc generator
          command: npm install -g https://github.com/StackStorm/st2apidocgen
      - run:
          name: Generate API documentation
          command: st2apidocgen --render --output
      - store_artifacts:
          path: ~/st2apidocs/build
          destination: build
      - deploy:
          name: Installing deploy dependencies
          command: |
            apt -y update
            apt -y install unzip
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
            aws configure set preview.cloudfront true
      - deploy:
          name: Deploying to S3
          command: |
            find ~/st2apidocs/build | sed 's|[^/]*/|  |g'
            aws s3 sync build/ s3://api-staging.stackstorm.com/${CIRCLE_BUILD_NUM} --region ${REGION}
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 sync build/ s3://api.stackstorm.com/ --region ${REGION} --delete
              aws cloudfront create-invalidation --distribution-id=${DISTRIBUTION_ID} --paths="/*"
            fi
